[package]
name = "mesh_code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glm = "0.2.3"
macroquad = "0.3.25"
nalgebra = { version = "0.32.1", features = ["rand"] }
rand = "0.8.5"
rayon = "1.6.1"
